### ISSUE TITLE
Add css

### ISSUE THREAD

**Issue by nknaian** [nknaian/musicrecs#19]
Should probably relegate formatting to css files instead of directly in the html

**Comment by bricknj** [comment]
Just made a major breakthrough in successfully linking my css file to the html. Turns out it had been in the wrong folder for Flask, and all of my html debugging was irrelevant. Will actually add the styling to it tomorrow/the weekend.

**Comment by bricknj** [comment]
I see the err in my approach to the album art styling. I'll look into how to resolve that. I don't think it's a major issue.

**Comment by nknaian** [comment]
What's the problem with album art styling?
